### ISSUE TITLE
`mfa.enroll`'s return type has a TypeScript breaking change in v2.65.0

### ISSUE THREAD

**Issue by aloisklink** [supabase/auth-js#955]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

As of [v2.65.0](https://github.com/supabase/auth-js/releases/tag/v2.65.0) and https://github.com/supabase/auth-js/commit/b957c30782065e4cc421a526c62c101d35c443d4, the `mfa.enroll` function's return-type has changed, so that the following code in the official TOTP docs now throws a TypeScript error:

https://github.com/supabase/supabase/blob/7f0a216c40dafdd14ae99b7a6efe4801e8306144/apps/docs/content/guides/auth/auth-mfa/totp.mdx?plain=1#L122-L133

## To Reproduce

Add the following test to this repo:

```diff
diff --git a/test/GoTrueClient.test.ts b/test/GoTrueClient.test.ts
index 6378ae1..7d42651 100644
--- a/test/GoTrueClient.test.ts
+++ b/test/GoTrueClient.test.ts
@@ -904,6 +904,20 @@ describe('User management', () => {
   })
 })

+describe('MFA', () => {
+  test('enroll({factorType: "totp"}) returns totp', async () => {
+    const { data, error } = await authWithSession.mfa.enroll({
+      factorType: 'totp',
+    })
+
+    if (error) {
+      throw error
+    }
+
+    expect(data.totp.qr_code).not.toBeNull()
+  })
+})
+
 describe('GoTrueClient with storageisServer = true', () => {
   const originalWarn = console.warn
   let warnings: any[][] = []
```

Running the tests will then cause the following TypeScript error in v2.65.0, but not before v2.65.0:

```
> @supabase/auth-js@0.0.0 test:suite
> jest --runInBand

 FAIL  test/GoTrueClient.test.ts
  ● Test suite failed to run

    test/GoTrueClient.test.ts:917:17 - error TS2339: Property 'totp' does not exist on type '{ id: string; type: "totp"; totp: { qr_code: string; secret: string; uri: string; }; friendly_name?: string | undefined; } | { id: string; type: "phone"; friendly_name?: string | undefined; phone: string; }'.
      Property 'totp' does not exist on type '{ id: string; type: "phone"; friendly_name?: string | undefined; phone: string; }'.

    917     expect(data.totp.qr_code).not.toBeNull()
```

## Expected behavior

Either:

- Existing code should still function when updated to v2.65.0. E.g. the `mfa.enroll` function has types that say it never returns a `type: "phone"` when `factorType: "totp"` is passed. This could be done by using either
  - TypeScript's function overloads: https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads
    - I've got a WIP PR that seems to work locally for this.
  - TypeScript's generic functions: https://www.typescriptlang.org/docs/handbook/2/functions.html#generic-functions

- If this is not possible, at least updating the docs in https://github.com/supabase/supabase/blob/7f0a216c40dafdd14ae99b7a6efe4801e8306144/apps/docs/content/guides/auth/auth-mfa/totp.mdx?plain=1#L122-L133

## Screenshots

N/A

## System information

- OS: Linux
- Version of supabase-js: [v2.45.3](https://github.com/supabase/supabase-js/releases/tag/v2.45.3) has this issue, [v2.45.2](https://github.com/supabase/supabase-js/releases/tag/v2.45.2) does not (probably due to https://github.com/supabase/supabase-js/commit/ef76013a74c7f9042ab0b06ea363476048467b27
- Version of Node.js: v20.17.0
- Version of TypeScript: 5.5.4

## Additional context

N/A
